namespace BudgetApp.Api.Models.Entities;

/// <summary>
/// Server-side Category entity. Mirrors BudgetApp.Shared.Models.Category
/// but adds UserId (multi-tenant), SyncId (for matching with the client),
/// and audit/soft-delete fields for sync.
/// </summary>
public class Category
{
    public int Id { get; set; }

    /// <summary>
    /// A globally unique ID generated by the client when the record is first created.
    /// Used to match this server record to the client's local SQLite record during sync.
    /// </summary>
    public Guid SyncId { get; set; }

    /// <summary>
    /// FK to AppUser -- every record is owned by exactly one user.
    /// All queries filter by UserId so users never see each other's data.
    /// </summary>
    public string UserId { get; set; } = string.Empty;

    public string Name { get; set; } = string.Empty;
    public string Icon { get; set; } = string.Empty;
    public string Color { get; set; } = string.Empty;
    public decimal DefaultBudget { get; set; }
    public CategoryType Type { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    public bool IsDeleted { get; set; }

    // Navigation properties
    public AppUser User { get; set; } = null!;
}
